import os
import json
import subprocess
import time
import uuid
from pathlib import Path

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich.markup import escape

from dck.oci import pull_image as oci_pull, list_images as oci_list
from dck.i18n import t
from dck.port import open_container_ports

console = Console()
PAPER_VERSIONS_FILE = Path(__file__).parent / "paper_versions.json"


# ── helpers ──────────────────────────────────────────────────────────


def _get_server_ip():
    try:
        r = subprocess.run(
            ["curl", "-s", "--max-time", "3", "https://ifconfig.me"],
            capture_output=True, text=True, timeout=5,
        )
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip()
    except Exception:
        pass
    try:
        r = subprocess.run(
            ["curl", "-s", "--max-time", "3", "https://api.ipify.org"],
            capture_output=True, text=True, timeout=5,
        )
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip()
    except Exception:
        pass
    try:
        r = subprocess.run(
            ["hostname", "-I"], capture_output=True, text=True, timeout=3,
        )
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip().split()[0]
    except Exception:
        pass
    return None


def _validate_memory(mem_str):
    if not mem_str:
        return None
    mem_str = str(mem_str).strip().lower()
    if mem_str[-1].isdigit():
        mem_str += "m"
    unit = mem_str[-1]
    if unit not in ("b", "k", "m", "g", "t"):
        console.print(f"[red]{t('memory.invalid')}[/red]")
        return None
    num_part = mem_str[:-1]
    if not num_part.isdigit():
        console.print(f"[red]{t('memory.invalid')}[/red]")
        return None
    multipliers = {"b": 1, "k": 1024, "m": 1024**2, "g": 1024**3, "t": 1024**4}
    return int(num_part) * multipliers[unit]


def _parse_cpu(cpu_str):
    try:
        return int(float(cpu_str) * 1e9)
    except (ValueError, TypeError):
        return None


def _load_paper_versions():
    try:
        data = json.loads(PAPER_VERSIONS_FILE.read_text())
        return data.get("latest"), data.get("versions", {})
    except Exception:
        return None, {}


def _ask_paper_version():
    latest, versions = _load_paper_versions()
    if not versions:
        return None

    stable = {k: v for k, v in versions.items() if "-" not in k}
    stable_sorted = sorted(stable.keys(), key=lambda x: [int(p) if p.isdigit() else p for p in x.split(".")], reverse=True)

    console.print(f"\n[bold]Paper versions[/bold]  latest: [cyan]{latest}[/cyan]")
    console.print("[dim]Select version or leave empty for latest[/dim]\n")

    table = Table(border_style="cyan", box=None, show_header=False, padding=(0, 2))
    table.add_column("#", style="bold", width=3)
    table.add_column("Version")
    table.add_column("Build")

    recent = stable_sorted[:16]
    for i, ver in enumerate(recent, 1):
        url = stable[ver]
        build = url.split("-")[-1].replace(".jar", "")
        label = f"[green]{ver}[/green]" if ver == latest else ver
        table.add_row(str(i), label, build)

    console.print(table)

    if len(stable) > 16:
        console.print(f"  [dim]... and {len(stable) - 16} older versions (edit run.sh to use them)[/dim]")

    choice = Prompt.ask("  Paper version", default=str(recent.index(latest) + 1) if latest in recent else "1")
    try:
        idx = int(choice) - 1
        if 0 <= idx < len(recent):
            ver = recent[idx]
            return ver, stable[ver]
    except ValueError:
        pass
    if choice in versions:
        return choice, versions[choice]
    if not choice and latest:
        return latest, versions.get(latest)
    return None


def _download_jar(url, dest_path):
    import urllib.request
    console.print(f"  [dim]Downloading Paper...[/dim]")
    try:
        urllib.request.urlretrieve(url, str(dest_path))
        size = dest_path.stat().st_size
        console.print(f"  [green]✓[/green] Downloaded [bold]{size // 1024 // 1024}MB[/bold]")
        return True
    except Exception as e:
        console.print(f"  [red]Download failed: {e}[/red]")
        return False


# ── create launcher (run.sh) ────────────────────────────────────────


def _create_data_launcher(container_name, image, vol_path, ports, env_vars, ram, cpu):
    parts = [
        "#!/usr/bin/env bash",
        f"# {container_name} - Game server launcher (native dck runtime)",
        "# Generated by dck",
        "",
        f'NAME="{container_name}"',
        f'IMAGE="{image}"',
        "",
        'echo "==> Stopping old container..."',
        f'dck stop "$NAME" 2>/dev/null || true',
        f'dck rm "$NAME" 2>/dev/null || true',
        "",
        'echo "==> Starting $NAME..."',
    ]

    cmd = f'dck run -d --name "$NAME"'
    cmd += f' --restart unless-stopped'

    for c_port, h_port in (ports or {}).items():
        c_num = c_port.split("/")[0]
        proto = c_port.split("/")[1] if "/" in c_port else "tcp"
        cmd += f" -p {h_port}:{c_num}/{proto}"

    for k, v in (env_vars or {}).items():
        if v:
            cmd += f" -e {k}={v}"

    cmd += f' -v "$(pwd):/data"'
    if ram:
        cmd += f" --ram {ram}"
    if cpu:
        cmd += f" --cpu {cpu}"
    cmd += " -e TYPE=CUSTOM -e CUSTOM_SERVER=/data/server.jar"
    cmd += " -e VERSION= -e EULA=TRUE -t -i"
    cmd += f' "$IMAGE"'

    parts.append(cmd)
    parts.append("")
    parts.append(f'echo "==> Server started. Use \'dck exec -it {container_name}\' to connect."')
    parts.append(f'echo "    Or: dck exec -it {container_name} /bin/bash"')

    return "\n".join(parts) + "\n"


# ── summary panels ──────────────────────────────────────────────────


def _show_creation_summary(name, ports, env_vars, volumes, ram, cpu, paper_version=None):
    ip = _get_server_ip()
    panel_lines = []
    if name:
        panel_lines.append(f"[bold]Name:[/bold] {escape(name)}")
    if ram:
        panel_lines.append(f"[bold]RAM:[/bold] {escape(ram)}")
    if cpu:
        panel_lines.append(f"[bold]CPU:[/bold] {escape(cpu)} cores")
    if paper_version:
        panel_lines.append(f"[bold]Paper:[/bold] [cyan]{escape(paper_version)}[/cyan]")
    for c_port, h_port in (ports or {}).items():
        proto = c_port.split("/")[1] if "/" in c_port else "tcp"
        c_num = c_port.split("/")[0]
        port_str = f"  [cyan]{h_port}:{c_num}/{proto}[/cyan]"
        if ip and proto == "tcp":
            port_str += f"  [dim]→ http://{ip}:{h_port}[/dim]"
        panel_lines.append(f"[bold]Port:[/bold]{port_str}")
    for h_path, cfg in (volumes or {}).items():
        panel_lines.append(f"[bold]Volume:[/bold] {escape(h_path)} [dim]→ {cfg['bind']}[/dim]")
    for k, v in (env_vars or {}).items():
        if v:
            panel_lines.append(f"[bold]Env:[/bold] {escape(k)}={escape(v)}")
    panel_content = "\n".join(panel_lines) if panel_lines else "  [dim](no configuration)[/dim]"
    console.print(Panel.fit(panel_content, border_style="cyan"))


def _show_container_summary(container, container_name, image, ports, volumes, env_vars, ram, cpu):
    table = Table(border_style="cyan")
    table.add_column("Property", style="bold")
    table.add_column("Value")
    table.add_row("Name", container_name)
    table.add_row("Image", escape(image))
    status_style = "green" if container.status == "running" else "yellow"
    table.add_row("Status", f"[{status_style}]{container.status}[/{status_style}]")
    if ram:
        table.add_row("RAM", ram)
    if cpu:
        table.add_row("CPU", f"{cpu} cores")
    for c_port, h_port in (ports or {}).items():
        c_num = c_port.split("/")[0]
        proto = c_port.split("/")[1] if "/" in c_port else "tcp"
        table.add_row("Port", f"{h_port}:{c_num}/{proto}")
    for h_path, cfg in (volumes or {}).items():
        table.add_row("Volume", f"{h_path} → {cfg['bind']}")
    console.print(table)


# ── prompt helpers ──────────────────────────────────────────────────


def _ask_ports():
    ports = {}
    console.print(f"\n[bold]{t('port.mappings')}[/bold]")

    first = Prompt.ask("  Port mapping", default="", show_default=False)
    if first:
        parts = first.split(":")
        if len(parts) == 2:
            h_port, rest = parts
            if "/" in rest:
                c_port, proto = rest.split("/", 1)
            else:
                c_port = rest
                proto = "tcp"
            try:
                ports[f"{c_port}/{proto}"] = int(h_port)
            except ValueError:
                console.print(f"[red]{t('port.invalid')}[/red]")

    while True:
        extra = Prompt.ask(f"  {t('port.extra')}", default="", show_default=False)
        if not extra:
            break
        parts = extra.split(":")
        if len(parts) == 2:
            h_port, rest = parts
            if "/" in rest:
                c_port, proto = rest.split("/", 1)
            else:
                c_port = rest
                proto = "tcp"
            try:
                ports[f"{c_port}/{proto}"] = int(h_port)
            except ValueError:
                console.print(f"[red]{t('port.invalid')}[/red]")
        else:
            console.print(f"[red]{t('port.invalid')}[/red]")
    return ports


def _ask_volumes():
    volumes = {}
    console.print(f"\n[bold]{t('volume.mounts')}[/bold]")

    first = Prompt.ask("  Volume mount (host:container)", default="", show_default=False)
    if first:
        parts = first.split(":", 1)
        if len(parts) == 2:
            host_path, container_path = parts
            host_path = os.path.expanduser(host_path)
            if not os.path.exists(host_path):
                os.makedirs(host_path, exist_ok=True)
                console.print(f"  [dim]{t('volume.notfound', path=host_path)}[/dim]")
            volumes[host_path] = {"bind": container_path, "mode": "rw"}
        else:
            console.print(f"[red]{t('volume.invalid')}[/red]")

    while True:
        extra = Prompt.ask(f"  {t('volume.extra')}", default="", show_default=False)
        if not extra:
            break
        parts = extra.split(":", 1)
        if len(parts) == 2:
            host_path, container_path = parts
            host_path = os.path.expanduser(host_path)
            if not os.path.exists(host_path):
                os.makedirs(host_path, exist_ok=True)
                console.print(f"  [dim]{t('volume.notfound', path=host_path)}[/dim]")
            volumes[host_path] = {"bind": container_path, "mode": "rw"}
        else:
            console.print(f"[red]{t('volume.invalid')}[/red]")
    return volumes


def _ask_env():
    env_vars = {}
    console.print(f"\n[bold]{t('env.vars')}[/bold]")

    first = Prompt.ask("  Environment (KEY=VALUE)", default="", show_default=False)
    if first:
        if "=" in first:
            k, v = first.split("=", 1)
            env_vars[k.strip()] = v.strip()
        else:
            console.print(f"[red]{t('env.invalid')}[/red]")

    while True:
        extra = Prompt.ask(f"  {t('env.extra')}", default="", show_default=False)
        if not extra:
            break
        if "=" in extra:
            k, v = extra.split("=", 1)
            env_vars[k.strip()] = v.strip()
        else:
            console.print(f"[red]{t('env.invalid')}[/red]")
    return env_vars


def _ask_resources(default_ram="512m", default_cpu="1"):
    ram = Prompt.ask(f"  {t('ram.limit')}", default=default_ram)
    cpu = Prompt.ask(f"  {t('cpu.limit')}", default=default_cpu)
    return ram, cpu


# ── build & start ───────────────────────────────────────────────────


def build_and_start(image, name, ports, env_vars, volumes, ram, cpu, start_now=True, paper_info=None):
    is_game = paper_info is not None

    # Pull image
    tag = "latest"
    if ":" in image:
        image, tag = image.split(":", 1)

    with console.status(f"{t('pulling')} [cyan]{escape(image)}[/cyan]..."):
        try:
            oci_pull(image, tag)
        except Exception as e:
            console.print(f"[red]{t('error')}:[/red] {e}")
            return None

    if paper_info and volumes:
        paper_version, paper_url = paper_info
        vol_path = list(volumes.keys())[0]
        jar_dest = Path(vol_path) / "server.jar"
        _download_jar(paper_url, jar_dest)

    container_name = name or f"{image.split('/')[-1].split(':')[0]}-{os.urandom(4).hex()}"

    container_env = dict(env_vars) if env_vars else {}
    if is_game:
        container_env["TYPE"] = "CUSTOM"
        container_env["CUSTOM_SERVER"] = "/data/server.jar"

    # Convert volumes from Docker format to native format
    native_volumes = {}
    for h_path, cfg in (volumes or {}).items():
        native_volumes[h_path] = cfg["bind"]

    if is_game and volumes:
        # Game server: just download jar + generate run.sh, no container created
        vol_path = list(volumes.keys())[0]
        launcher = _create_data_launcher(container_name, image, vol_path, ports, env_vars, ram, cpu)
        launcher_path = Path(vol_path) / "run.sh"
        launcher_path.write_text(launcher)
        launcher_path.chmod(0o755)
        console.print(f"\n[green]✓ Server folder ready![/green]")
        console.print(f"  [bold]{vol_path}[/bold]")
        if paper_info:
            console.print(f"  [green]✓[/green] Paper jar: [bold]{vol_path}/server.jar[/bold]")
        console.print(f"  [green]✓[/green] Launcher: [bold]{vol_path}/run.sh[/bold]")
        console.print(f"\n  [dim]Run: cd {vol_path} && ./run.sh[/dim]")
        open_container_ports(container_name, ports)

        class FakeContainer:
            def __init__(self):
                self.status = "created"
                self.name = container_name
        _show_container_summary(FakeContainer(), container_name, image, ports, volumes, container_env, ram, cpu)
        return container_name

    # Non-game: create and start the container
    img_info = None
    for i in oci_list():
        if i["name"] == image and i["tag"] == tag:
            img_info = i
            break

    if not img_info:
        console.print(f"[red]Image {image}:{tag} not found after pull[/red]")
        return None

    rootfs = img_info["rootfs"]
    img_config = {}
    cfg_file = Path.home() / ".dck" / "images" / image.replace("/", "_") / tag / "config.json"
    if cfg_file.exists():
        try:
            img_config = json.loads(cfg_file.read_text()).get("config", {})
        except Exception:
            pass

    img_env = {}
    for e in img_config.get("Env", []):
        if "=" in e:
            k, v = e.split("=", 1)
            img_env[k] = v
    full_env = {**img_env, **container_env}

    command = (img_config.get("Entrypoint", []) + img_config.get("Cmd", [])) or ["/bin/sh"]

    container_config = {
        "image": f"{image}:{tag}",
        "command": command,
        "rootfs": rootfs,
        "ports": dict(ports) if ports else {},
        "volumes": native_volumes,
        "env": full_env,
        "ram": ram,
        "cpu": cpu,
        "tty": False,
        "interactive": False,
        "detach": True,
        "rm": False,
    }

    from dck.runtime import Container
    container = Container(name=container_name, config=container_config)
    container.create()
    console.print(f"\n[green]{t('created')}![/green]")
    console.print(f"  Name: [bold]{container_name}[/bold]")
    console.print(f"  Image: {escape(image)}")

    if start_now:
        with console.status("Starting..."):
            container.start()
            time.sleep(0.5)

        if container.get_status() == "running":
            ip = _get_server_ip()
            console.print(f"  {t('status.running')}: [green]{t('container.running')}[/green]")
            for c_port, h_port in (ports or {}).items():
                c_num = c_port.split("/")[0]
                proto = c_port.split("/")[1] if "/" in c_port else "tcp"
                line = f"  {t('port.info')}: [bold]{h_port}:{c_num}/{proto}[/bold]"
                if ip and proto == "tcp":
                    line += f"  [dim]→ http://{ip}:{h_port}[/dim]"
                console.print(line)
        else:
            logs = container.logs(tail=30)
            console.print(f"  [red]{t('container.exited')}[/red]")
            if logs:
                console.print(f"  [dim]{logs.strip().split(chr(10))[-1]}[/dim]")

    open_container_ports(container_name, ports)

    cstatus = container.get_status()
    class FakeContainer:
        def __init__(self, status, name):
            self.status = status
            self.name = name
    fake_ctn = FakeContainer(cstatus, container_name)
    _show_container_summary(fake_ctn, container_name, image, ports, volumes, container_env, ram, cpu)

    console.print(f"\n[dim]{t('manage.hint')}: dck ps | dck logs {container_name} | dck stop {container_name}[/dim]")

    if cstatus == "running":
        console.print(f"  [dim]Connect: dck exec -it {container_name} /bin/sh[/dim]")

    return container_name


# ── public entry points ─────────────────────────────────────────────


def create_interactive(image=None, name=None, ram=None, cpu=None, port=None, env=None, volume=None, paper=False):
    if not image:
        image = Prompt.ask("  Docker image", default="nginx:alpine")

    is_game = paper or "minecraft" in image.lower()

    def _parse_ports(p_list):
        result = {}
        for p in (p_list or []):
            parts = p.split(":")
            if len(parts) == 2:
                h_port, rest = parts
                if "/" in rest:
                    c_port, proto = rest.split("/", 1)
                else:
                    c_port = rest
                    proto = "tcp"
                try:
                    result[f"{c_port}/{proto}"] = int(h_port)
                except ValueError:
                    pass
        return result

    def _parse_env(e_list):
        result = {}
        for e in (e_list or []):
            if "=" in e:
                k, v = e.split("=", 1)
                result[k.strip()] = v.strip()
        return result

    def _parse_volumes(v_list):
        result = {}
        for v in (v_list or []):
            parts = v.split(":", 1)
            if len(parts) == 2:
                host_path, container_path = parts
                host_path = os.path.expanduser(host_path)
                if not os.path.exists(host_path):
                    os.makedirs(host_path, exist_ok=True)
                result[host_path] = {"bind": container_path, "mode": "rw"}
        return result

    ports_input = _parse_ports(port)
    env_input = _parse_env(env)
    volumes_input = _parse_volumes(volume)

    if not port:
        ports_input = _ask_ports()
    else:
        for c_p in list(ports_input.keys()):
            console.print(f"  Port: [cyan]{ports_input[c_p]}:{c_p}[/cyan]")

    if not env:
        env_input = _ask_env()
    else:
        for k, v in env_input.items():
            console.print(f"  Env: [dim]{k}={v}[/dim]")

    if not volume:
        volumes_input = _ask_volumes()
    else:
        for h_p in list(volumes_input.keys()):
            console.print(f"  Volume: {h_p} [dim]→ {volumes_input[h_p]['bind']}[/dim]")

    if ram and cpu:
        ram_cfg, cpu_cfg = ram, cpu
    else:
        ram_cfg, cpu_cfg = _ask_resources(ram or "512m", cpu or "1")

    paper_info = None
    if is_game:
        result = _ask_paper_version()
        if result:
            paper_info = result

    suggested_name = name or f"{image.split('/')[-1].split(':')[0]}-{os.urandom(4).hex()}"
    name = Prompt.ask("  Container name", default=suggested_name)

    _show_creation_summary(name, ports_input, env_input, volumes_input, ram_cfg, cpu_cfg,
                          paper_version=paper_info[0] if paper_info else None)

    if not Confirm.ask("\n[bold]Build this container?[/bold]", default=True):
        console.print("[yellow]Cancelled[/yellow]")
        return

    build_and_start(image, name, ports_input, env_input, volumes_input, ram_cfg, cpu_cfg,
                   paper_info=paper_info)


def run_custom(image, name, ram, cpu):
    """Quick custom container: prompts for ports/volumes/env but skips template selection."""
    is_game = "minecraft" in image.lower()

    if not ram and not cpu:
        ram, cpu = _ask_resources()

    paper_info = None
    if is_game:
        result = _ask_paper_version()
        if result:
            paper_info = result

    ports = _ask_ports()
    volumes = _ask_volumes()
    env_vars = _ask_env()

    suggested_name = name or f"{image.split('/')[-1].split(':')[0]}-{os.urandom(4).hex()}"
    name = Prompt.ask("  Container name", default=suggested_name)

    _show_creation_summary(name, ports, env_vars, volumes, ram, cpu,
                          paper_version=paper_info[0] if paper_info else None)

    if not Confirm.ask("\n[bold]Build this container?[/bold]", default=True):
        console.print("[yellow]Cancelled[/yellow]")
        return

    build_and_start(image, name, ports, env_vars, volumes, ram, cpu, paper_info=paper_info)
